file=open('text2.txt','r')
print(file.read())
file.close()
file=open('text3.txt','w')
file.write("welcome to my class")
file=open('text3.txt','r')
print(file.read())
file=open('text3.txt','a')
file.write("\n this is Rajashree's computer class")
file.close()
print("\nfile content after appending\n")
file=open('text3.txt','r')
print(file.read())